{{- if .Values.nest.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app.kubernetes.io/name: {{ include "redis-sentinel.name" . }}-api
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: {{ include "redis-sentinel.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  type: {{ .Values.nest.service.type }}
  ports:
    - name: http
      port: {{ .Values.nest.service.port }}
      targetPort: http
  selector:
    app.kubernetes.io/name: {{ include "redis-sentinel.name" . }}-api
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
