{{- /*
SealedSecret for the Redis password. This requires the Sealed Secrets controller.
Encrypt your password using the controller's public key (or your ~/.ssh/id_rsa.pub if you configured the controller with that key)
and set redis.sealedSecret.encryptedPassword in values.yaml.
*/ -}}
{{- if not .Values.redis.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis-sentinel.fullname" . }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redis-sentinel.labels" . | nindent 4 }}
type: Opaque
stringData:
  redis-password: "{{ .Values.redis.password }}"
{{- end }}
