apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.headless.name }}
  labels:
    {{- include "redis-sentinel.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: redis
      port: {{ .Values.redis.port }}
      targetPort: redis
    - name: sentinel
      port: {{ .Values.sentinel.port }}
      targetPort: sentinel
  selector:
    app.kubernetes.io/name: {{ include "redis-sentinel.name" . }}
